/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.sohlman.liferay.bfdms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FileInfo service. Represents a row in the &quot;bfdms_FileInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.sohlman.liferay.bfdms.model.impl.FileInfoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.sohlman.liferay.bfdms.model.impl.FileInfoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FileInfo
 * @generated
 */
@ProviderType
public interface FileInfoModel extends BaseModel<FileInfo>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a file info model instance should use the {@link FileInfo} interface instead.
	 */

	/**
	 * Returns the primary key of this file info.
	 *
	 * @return the primary key of this file info
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this file info.
	 *
	 * @param primaryKey the primary key of this file info
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the file info ID of this file info.
	 *
	 * @return the file info ID of this file info
	 */
	public long getFileInfoId();

	/**
	 * Sets the file info ID of this file info.
	 *
	 * @param fileInfoId the file info ID of this file info
	 */
	public void setFileInfoId(long fileInfoId);

	/**
	 * Returns the company ID of this file info.
	 *
	 * @return the company ID of this file info
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this file info.
	 *
	 * @param companyId the company ID of this file info
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the repository ID of this file info.
	 *
	 * @return the repository ID of this file info
	 */
	public long getRepositoryId();

	/**
	 * Sets the repository ID of this file info.
	 *
	 * @param repositoryId the repository ID of this file info
	 */
	public void setRepositoryId(long repositoryId);

	/**
	 * Returns the path of this file info.
	 *
	 * @return the path of this file info
	 */
	@AutoEscape
	public String getPath();

	/**
	 * Sets the path of this file info.
	 *
	 * @param path the path of this file info
	 */
	public void setPath(String path);

	/**
	 * Returns the version of this file info.
	 *
	 * @return the version of this file info
	 */
	@AutoEscape
	public String getVersion();

	/**
	 * Sets the version of this file info.
	 *
	 * @param version the version of this file info
	 */
	public void setVersion(String version);

	/**
	 * Returns the file data ID of this file info.
	 *
	 * @return the file data ID of this file info
	 */
	public long getFileDataId();

	/**
	 * Sets the file data ID of this file info.
	 *
	 * @param fileDataId the file data ID of this file info
	 */
	public void setFileDataId(long fileDataId);

	@Override
	public FileInfo cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}