/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.sohlman.liferay.bfdms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FileData service. Represents a row in the &quot;bfdms_FileData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.sohlman.liferay.bfdms.model.impl.FileDataModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.sohlman.liferay.bfdms.model.impl.FileDataImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FileData
 * @generated
 */
@ProviderType
public interface FileDataModel extends BaseModel<FileData>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a file data model instance should use the {@link FileData} interface instead.
	 */

	/**
	 * Returns the primary key of this file data.
	 *
	 * @return the primary key of this file data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this file data.
	 *
	 * @param primaryKey the primary key of this file data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the file data ID of this file data.
	 *
	 * @return the file data ID of this file data
	 */
	public long getFileDataId();

	/**
	 * Sets the file data ID of this file data.
	 *
	 * @param fileDataId the file data ID of this file data
	 */
	public void setFileDataId(long fileDataId);

	/**
	 * Returns the company ID of this file data.
	 *
	 * @return the company ID of this file data
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this file data.
	 *
	 * @param companyId the company ID of this file data
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this file data.
	 *
	 * @return the create date of this file data
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this file data.
	 *
	 * @param createDate the create date of this file data
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the name of this file data.
	 *
	 * @return the name of this file data
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this file data.
	 *
	 * @param name the name of this file data
	 */
	public void setName(String name);

	/**
	 * Returns the size of this file data.
	 *
	 * @return the size of this file data
	 */
	public long getSize();

	/**
	 * Sets the size of this file data.
	 *
	 * @param size the size of this file data
	 */
	public void setSize(long size);

	/**
	 * Returns the fingerprint of this file data.
	 *
	 * @return the fingerprint of this file data
	 */
	@AutoEscape
	public String getFingerprint();

	/**
	 * Sets the fingerprint of this file data.
	 *
	 * @param fingerprint the fingerprint of this file data
	 */
	public void setFingerprint(String fingerprint);

	@Override
	public FileData cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}