/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.sohlman.liferay.bffss.model.impl;

import com.sohlman.liferay.bffss.model.FileData;
import com.sohlman.liferay.bffss.service.FileDataLocalServiceUtil;

/**
 * The extended model base implementation for the FileData service. Represents a row in the &quot;bffss_FileData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FileDataImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FileDataImpl
 * @see FileData
 * @generated
 */
public abstract class FileDataBaseImpl
	extends FileDataModelImpl implements FileData {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a file data model instance should use the <code>FileData</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			FileDataLocalServiceUtil.addFileData(this);
		}
		else {
			FileDataLocalServiceUtil.updateFileData(this);
		}
	}

}