/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.sohlman.liferay.bffss.model.impl;

import com.sohlman.liferay.bffss.model.FileInfo;
import com.sohlman.liferay.bffss.service.FileInfoLocalServiceUtil;

/**
 * The extended model base implementation for the FileInfo service. Represents a row in the &quot;bffss_FileInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FileInfoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FileInfoImpl
 * @see FileInfo
 * @generated
 */
public abstract class FileInfoBaseImpl
	extends FileInfoModelImpl implements FileInfo {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a file info model instance should use the <code>FileInfo</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			FileInfoLocalServiceUtil.addFileInfo(this);
		}
		else {
			FileInfoLocalServiceUtil.updateFileInfo(this);
		}
	}

}