/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.sohlman.liferay.bffss.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.sohlman.liferay.bffss.model.FileData;
import com.sohlman.liferay.bffss.model.FileDataModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FileData service. Represents a row in the &quot;bffss_FileData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FileDataModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FileDataImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FileDataImpl
 * @generated
 */
public class FileDataModelImpl
	extends BaseModelImpl<FileData> implements FileDataModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a file data model instance should use the <code>FileData</code> interface instead.
	 */
	public static final String TABLE_NAME = "bffss_FileData";

	public static final Object[][] TABLE_COLUMNS = {
		{"fileDataId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"size_", Types.BIGINT}, {"fingerprint", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("fileDataId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("size_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fingerprint", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table bffss_FileData (fileDataId LONG not null primary key,companyId LONG,createDate DATE null,name VARCHAR(75) null,size_ LONG,fingerprint VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table bffss_FileData";

	public static final String ORDER_BY_JPQL =
		" ORDER BY fileData.fileDataId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY bffss_FileData.fileDataId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FINGERPRINT_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FILEDATAID_COLUMN_BITMASK = 2L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.sohlman.liferay.bffss.service.util.PropsUtil.get(
			"lock.expiration.time.com.sohlman.liferay.bffss.model.FileData"));

	public FileDataModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fileDataId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFileDataId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fileDataId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FileData.class;
	}

	@Override
	public String getModelClassName() {
		return FileData.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FileData, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FileData, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FileData, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((FileData)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FileData, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FileData, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FileData)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FileData, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FileData, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<FileData, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<FileData, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<FileData, Object>>();

			attributeGetterFunctions.put("fileDataId", FileData::getFileDataId);
			attributeGetterFunctions.put("companyId", FileData::getCompanyId);
			attributeGetterFunctions.put("createDate", FileData::getCreateDate);
			attributeGetterFunctions.put("name", FileData::getName);
			attributeGetterFunctions.put("size", FileData::getSize);
			attributeGetterFunctions.put(
				"fingerprint", FileData::getFingerprint);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<FileData, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<FileData, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<FileData, ?>>();

			attributeSetterBiConsumers.put(
				"fileDataId",
				(BiConsumer<FileData, Long>)FileData::setFileDataId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<FileData, Long>)FileData::setCompanyId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<FileData, Date>)FileData::setCreateDate);
			attributeSetterBiConsumers.put(
				"name", (BiConsumer<FileData, String>)FileData::setName);
			attributeSetterBiConsumers.put(
				"size", (BiConsumer<FileData, Long>)FileData::setSize);
			attributeSetterBiConsumers.put(
				"fingerprint",
				(BiConsumer<FileData, String>)FileData::setFingerprint);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getFileDataId() {
		return _fileDataId;
	}

	@Override
	public void setFileDataId(long fileDataId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileDataId = fileDataId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@Override
	public long getSize() {
		return _size;
	}

	@Override
	public void setSize(long size) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_size = size;
	}

	@Override
	public String getFingerprint() {
		if (_fingerprint == null) {
			return "";
		}
		else {
			return _fingerprint;
		}
	}

	@Override
	public void setFingerprint(String fingerprint) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fingerprint = fingerprint;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalFingerprint() {
		return getColumnOriginalValue("fingerprint");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FileData.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FileData toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FileData>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FileDataImpl fileDataImpl = new FileDataImpl();

		fileDataImpl.setFileDataId(getFileDataId());
		fileDataImpl.setCompanyId(getCompanyId());
		fileDataImpl.setCreateDate(getCreateDate());
		fileDataImpl.setName(getName());
		fileDataImpl.setSize(getSize());
		fileDataImpl.setFingerprint(getFingerprint());

		fileDataImpl.resetOriginalValues();

		return fileDataImpl;
	}

	@Override
	public FileData cloneWithOriginalValues() {
		FileDataImpl fileDataImpl = new FileDataImpl();

		fileDataImpl.setFileDataId(
			this.<Long>getColumnOriginalValue("fileDataId"));
		fileDataImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		fileDataImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		fileDataImpl.setName(this.<String>getColumnOriginalValue("name"));
		fileDataImpl.setSize(this.<Long>getColumnOriginalValue("size_"));
		fileDataImpl.setFingerprint(
			this.<String>getColumnOriginalValue("fingerprint"));

		return fileDataImpl;
	}

	@Override
	public int compareTo(FileData fileData) {
		long primaryKey = fileData.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FileData)) {
			return false;
		}

		FileData fileData = (FileData)object;

		long primaryKey = fileData.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FileData> toCacheModel() {
		FileDataCacheModel fileDataCacheModel = new FileDataCacheModel();

		fileDataCacheModel.fileDataId = getFileDataId();

		fileDataCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			fileDataCacheModel.createDate = createDate.getTime();
		}
		else {
			fileDataCacheModel.createDate = Long.MIN_VALUE;
		}

		fileDataCacheModel.name = getName();

		String name = fileDataCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			fileDataCacheModel.name = null;
		}

		fileDataCacheModel.size = getSize();

		fileDataCacheModel.fingerprint = getFingerprint();

		String fingerprint = fileDataCacheModel.fingerprint;

		if ((fingerprint != null) && (fingerprint.length() == 0)) {
			fileDataCacheModel.fingerprint = null;
		}

		return fileDataCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FileData, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FileData, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FileData, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((FileData)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FileData>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					FileData.class, ModelWrapper.class);

	}

	private long _fileDataId;
	private long _companyId;
	private Date _createDate;
	private String _name;
	private long _size;
	private String _fingerprint;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<FileData, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FileData)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("fileDataId", _fileDataId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("size_", _size);
		_columnOriginalValues.put("fingerprint", _fingerprint);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("size_", "size");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("fileDataId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createDate", 4L);

		columnBitmasks.put("name", 8L);

		columnBitmasks.put("size_", 16L);

		columnBitmasks.put("fingerprint", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FileData _escapedModel;

}