package com.sohlman.liferay.bffss.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.sohlman.liferay.bffss.model.FileData;
import com.sohlman.liferay.bffss.service.FileDataLocalServiceUtil;

/**
 * The extended model base implementation for the FileData service. Represents a row in the &quot;bffss_FileData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FileDataImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FileDataImpl
 * @see com.sohlman.liferay.bffss.model.FileData
 * @generated
 */
public abstract class FileDataBaseImpl extends FileDataModelImpl
    implements FileData {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a file data model instance should use the {@link FileData} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            FileDataLocalServiceUtil.addFileData(this);
        } else {
            FileDataLocalServiceUtil.updateFileData(this);
        }
    }
}
