/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.sohlman.liferay.bfdms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.sohlman.liferay.bfdms.model.FileInfo;
import com.sohlman.liferay.bfdms.model.FileInfoModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FileInfo service. Represents a row in the &quot;bfdms_FileInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FileInfoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FileInfoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FileInfoImpl
 * @generated
 */
public class FileInfoModelImpl
	extends BaseModelImpl<FileInfo> implements FileInfoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a file info model instance should use the <code>FileInfo</code> interface instead.
	 */
	public static final String TABLE_NAME = "bfdms_FileInfo";

	public static final Object[][] TABLE_COLUMNS = {
		{"fileInfoId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"repositoryId", Types.BIGINT}, {"path_", Types.VARCHAR},
		{"version", Types.VARCHAR}, {"fileDataId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("fileInfoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("repositoryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("path_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("version", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fileDataId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table bfdms_FileInfo (fileInfoId LONG not null primary key,companyId LONG,repositoryId LONG,path_ VARCHAR(75) null,version VARCHAR(75) null,fileDataId LONG)";

	public static final String TABLE_SQL_DROP = "drop table bfdms_FileInfo";

	public static final String ORDER_BY_JPQL =
		" ORDER BY fileInfo.version DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY bfdms_FileInfo.version DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FILEDATAID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PATH_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long REPOSITORYID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long VERSION_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FileInfoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fileInfoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFileInfoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fileInfoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FileInfo.class;
	}

	@Override
	public String getModelClassName() {
		return FileInfo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FileInfo, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FileInfo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FileInfo, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((FileInfo)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FileInfo, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FileInfo, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FileInfo)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FileInfo, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FileInfo, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<FileInfo, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<FileInfo, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<FileInfo, Object>>();

			attributeGetterFunctions.put("fileInfoId", FileInfo::getFileInfoId);
			attributeGetterFunctions.put("companyId", FileInfo::getCompanyId);
			attributeGetterFunctions.put(
				"repositoryId", FileInfo::getRepositoryId);
			attributeGetterFunctions.put("path", FileInfo::getPath);
			attributeGetterFunctions.put("version", FileInfo::getVersion);
			attributeGetterFunctions.put("fileDataId", FileInfo::getFileDataId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<FileInfo, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<FileInfo, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<FileInfo, ?>>();

			attributeSetterBiConsumers.put(
				"fileInfoId",
				(BiConsumer<FileInfo, Long>)FileInfo::setFileInfoId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<FileInfo, Long>)FileInfo::setCompanyId);
			attributeSetterBiConsumers.put(
				"repositoryId",
				(BiConsumer<FileInfo, Long>)FileInfo::setRepositoryId);
			attributeSetterBiConsumers.put(
				"path", (BiConsumer<FileInfo, String>)FileInfo::setPath);
			attributeSetterBiConsumers.put(
				"version", (BiConsumer<FileInfo, String>)FileInfo::setVersion);
			attributeSetterBiConsumers.put(
				"fileDataId",
				(BiConsumer<FileInfo, Long>)FileInfo::setFileDataId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getFileInfoId() {
		return _fileInfoId;
	}

	@Override
	public void setFileInfoId(long fileInfoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileInfoId = fileInfoId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getRepositoryId() {
		return _repositoryId;
	}

	@Override
	public void setRepositoryId(long repositoryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_repositoryId = repositoryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalRepositoryId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("repositoryId"));
	}

	@Override
	public String getPath() {
		if (_path == null) {
			return "";
		}
		else {
			return _path;
		}
	}

	@Override
	public void setPath(String path) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_path = path;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPath() {
		return getColumnOriginalValue("path_");
	}

	@Override
	public String getVersion() {
		if (_version == null) {
			return "";
		}
		else {
			return _version;
		}
	}

	@Override
	public void setVersion(String version) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_version = version;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalVersion() {
		return getColumnOriginalValue("version");
	}

	@Override
	public long getFileDataId() {
		return _fileDataId;
	}

	@Override
	public void setFileDataId(long fileDataId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileDataId = fileDataId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFileDataId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("fileDataId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FileInfo.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FileInfo toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FileInfo>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FileInfoImpl fileInfoImpl = new FileInfoImpl();

		fileInfoImpl.setFileInfoId(getFileInfoId());
		fileInfoImpl.setCompanyId(getCompanyId());
		fileInfoImpl.setRepositoryId(getRepositoryId());
		fileInfoImpl.setPath(getPath());
		fileInfoImpl.setVersion(getVersion());
		fileInfoImpl.setFileDataId(getFileDataId());

		fileInfoImpl.resetOriginalValues();

		return fileInfoImpl;
	}

	@Override
	public FileInfo cloneWithOriginalValues() {
		FileInfoImpl fileInfoImpl = new FileInfoImpl();

		fileInfoImpl.setFileInfoId(
			this.<Long>getColumnOriginalValue("fileInfoId"));
		fileInfoImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		fileInfoImpl.setRepositoryId(
			this.<Long>getColumnOriginalValue("repositoryId"));
		fileInfoImpl.setPath(this.<String>getColumnOriginalValue("path_"));
		fileInfoImpl.setVersion(this.<String>getColumnOriginalValue("version"));
		fileInfoImpl.setFileDataId(
			this.<Long>getColumnOriginalValue("fileDataId"));

		return fileInfoImpl;
	}

	@Override
	public int compareTo(FileInfo fileInfo) {
		int value = 0;

		value = getVersion().compareTo(fileInfo.getVersion());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FileInfo)) {
			return false;
		}

		FileInfo fileInfo = (FileInfo)object;

		long primaryKey = fileInfo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FileInfo> toCacheModel() {
		FileInfoCacheModel fileInfoCacheModel = new FileInfoCacheModel();

		fileInfoCacheModel.fileInfoId = getFileInfoId();

		fileInfoCacheModel.companyId = getCompanyId();

		fileInfoCacheModel.repositoryId = getRepositoryId();

		fileInfoCacheModel.path = getPath();

		String path = fileInfoCacheModel.path;

		if ((path != null) && (path.length() == 0)) {
			fileInfoCacheModel.path = null;
		}

		fileInfoCacheModel.version = getVersion();

		String version = fileInfoCacheModel.version;

		if ((version != null) && (version.length() == 0)) {
			fileInfoCacheModel.version = null;
		}

		fileInfoCacheModel.fileDataId = getFileDataId();

		return fileInfoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FileInfo, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FileInfo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FileInfo, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((FileInfo)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FileInfo>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					FileInfo.class, ModelWrapper.class);

	}

	private long _fileInfoId;
	private long _companyId;
	private long _repositoryId;
	private String _path;
	private String _version;
	private long _fileDataId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<FileInfo, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FileInfo)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("fileInfoId", _fileInfoId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("repositoryId", _repositoryId);
		_columnOriginalValues.put("path_", _path);
		_columnOriginalValues.put("version", _version);
		_columnOriginalValues.put("fileDataId", _fileDataId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("path_", "path");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("fileInfoId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("repositoryId", 4L);

		columnBitmasks.put("path_", 8L);

		columnBitmasks.put("version", 16L);

		columnBitmasks.put("fileDataId", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FileInfo _escapedModel;

}